name: WGRegionEffects
main: com.paramonod.WGRegionEffects.WGRegionEffectsPlugin
description: 'WorldGuard extension to let players automatically get a potion effect when they enter the region and lose it when they leave the region.'
version: 1.4

authors: [ paramonod ]
depend: [ WorldGuard ]
softdepend: [ WorldEdit ]

commands:
  toggleeffects:
    usage: /<command>
    permission: effects.toggle
    aliases: [ te ]

permissions:
  effects.toggle:
    description: Allows usage of the /<toggleeffects|te> command.
    default: true
    children: []
